// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { GetConversationsApiUsersUserIdConversationsGetData, GetConversationsApiUsersUserIdConversationsGetResponses, GetConversationsApiUsersUserIdConversationsGetErrors, GetConversationMessagesApiUsersUserIdConversationsConversationIdMessagesGetData, GetConversationMessagesApiUsersUserIdConversationsConversationIdMessagesGetResponses, GetConversationMessagesApiUsersUserIdConversationsConversationIdMessagesGetErrors, CreateConversationMessageApiUsersUserIdConversationsConversationIdMessagePostData, CreateConversationMessageApiUsersUserIdConversationsConversationIdMessagePostResponses, CreateConversationMessageApiUsersUserIdConversationsConversationIdMessagePostErrors, CreateConversationAndMessageApiUsersUserIdMessagesPostData, CreateConversationAndMessageApiUsersUserIdMessagesPostResponses, CreateConversationAndMessageApiUsersUserIdMessagesPostErrors, HealthCheckHealthGetData, HealthCheckHealthGetResponses, RootGetData, RootGetResponses } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get Conversations
 * Get conversations for a specific user
 */
export const getConversationsApiUsersUserIdConversationsGet = <ThrowOnError extends boolean = false>(options: Options<GetConversationsApiUsersUserIdConversationsGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetConversationsApiUsersUserIdConversationsGetResponses, GetConversationsApiUsersUserIdConversationsGetErrors, ThrowOnError>({
        url: '/api/users/{user_id}/conversations',
        ...options
    });
};

/**
 * Get Conversation Messages
 * Get all messages for a specific conversation
 */
export const getConversationMessagesApiUsersUserIdConversationsConversationIdMessagesGet = <ThrowOnError extends boolean = false>(options: Options<GetConversationMessagesApiUsersUserIdConversationsConversationIdMessagesGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetConversationMessagesApiUsersUserIdConversationsConversationIdMessagesGetResponses, GetConversationMessagesApiUsersUserIdConversationsConversationIdMessagesGetErrors, ThrowOnError>({
        url: '/api/users/{user_id}/conversations/{conversation_id}/messages',
        ...options
    });
};

/**
 * Create Conversation Message
 * Send a message to a specific conversation and get AI career advice
 */
export const createConversationMessageApiUsersUserIdConversationsConversationIdMessagePost = <ThrowOnError extends boolean = false>(options: Options<CreateConversationMessageApiUsersUserIdConversationsConversationIdMessagePostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateConversationMessageApiUsersUserIdConversationsConversationIdMessagePostResponses, CreateConversationMessageApiUsersUserIdConversationsConversationIdMessagePostErrors, ThrowOnError>({
        url: '/api/users/{user_id}/conversations/{conversation_id}/message',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Create Conversation And Message
 * Create a new conversation with the first message and get AI response
 */
export const createConversationAndMessageApiUsersUserIdMessagesPost = <ThrowOnError extends boolean = false>(options: Options<CreateConversationAndMessageApiUsersUserIdMessagesPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateConversationAndMessageApiUsersUserIdMessagesPostResponses, CreateConversationAndMessageApiUsersUserIdMessagesPostErrors, ThrowOnError>({
        url: '/api/users/{user_id}/messages',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Health Check
 */
export const healthCheckHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckHealthGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<HealthCheckHealthGetResponses, unknown, ThrowOnError>({
        url: '/health',
        ...options
    });
};

/**
 * Root
 */
export const rootGet = <ThrowOnError extends boolean = false>(options?: Options<RootGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<RootGetResponses, unknown, ThrowOnError>({
        url: '/',
        ...options
    });
};