// This file is auto-generated by @hey-api/openapi-ts

/**
 * PromptBase
 */
export type PromptBase = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Prompt Text
     */
    prompt_text: string;
};

/**
 * PromptListResponse
 */
export type PromptListResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Prompts
     */
    prompts: Array<PromptBase>;
};

export type GetPromptsApiPromptsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/prompts';
};

export type GetPromptsApiPromptsGetResponses = {
    /**
     * Successful Response
     */
    200: PromptListResponse;
};

export type GetPromptsApiPromptsGetResponse = GetPromptsApiPromptsGetResponses[keyof GetPromptsApiPromptsGetResponses];

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://localhost:8004' | (string & {});
};