// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { GetUserProfileApiUsersUserIdProfileGetData, GetUserProfileApiUsersUserIdProfileGetResponses, GetUserProfileApiUsersUserIdProfileGetErrors, HealthCheckHealthGetData, HealthCheckHealthGetResponses, RootGetData, RootGetResponses } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get User Profile
 * Get user profile by user ID.
 */
export const getUserProfileApiUsersUserIdProfileGet = <ThrowOnError extends boolean = false>(options: Options<GetUserProfileApiUsersUserIdProfileGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetUserProfileApiUsersUserIdProfileGetResponses, GetUserProfileApiUsersUserIdProfileGetErrors, ThrowOnError>({
        url: '/api/users/{user_id}/profile',
        ...options
    });
};

/**
 * Health Check
 */
export const healthCheckHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckHealthGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<HealthCheckHealthGetResponses, unknown, ThrowOnError>({
        url: '/health',
        ...options
    });
};

/**
 * Root
 */
export const rootGet = <ThrowOnError extends boolean = false>(options?: Options<RootGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<RootGetResponses, unknown, ThrowOnError>({
        url: '/',
        ...options
    });
};