// This file is auto-generated by @hey-api/openapi-ts

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * UserProfileBase
 */
export type UserProfileBase = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Years Experience
     */
    years_experience?: number | null;
    /**
     * Skills
     */
    skills?: Array<string> | null;
    /**
     * Career Goals
     */
    career_goals?: string | null;
    /**
     * Preferred Work Style
     */
    preferred_work_style?: string | null;
};

/**
 * UserProfileResponse
 */
export type UserProfileResponse = {
    /**
     * Success
     */
    success: boolean;
    profile?: UserProfileBase | null;
    /**
     * Message
     */
    message?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GetUserProfileApiUsersUserIdProfileGetData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/users/{user_id}/profile';
};

export type GetUserProfileApiUsersUserIdProfileGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserProfileApiUsersUserIdProfileGetError = GetUserProfileApiUsersUserIdProfileGetErrors[keyof GetUserProfileApiUsersUserIdProfileGetErrors];

export type GetUserProfileApiUsersUserIdProfileGetResponses = {
    /**
     * Successful Response
     */
    200: UserProfileResponse;
};

export type GetUserProfileApiUsersUserIdProfileGetResponse = GetUserProfileApiUsersUserIdProfileGetResponses[keyof GetUserProfileApiUsersUserIdProfileGetResponses];

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://localhost:8001' | (string & {});
};